zara:
    xauth:
        secret-key: 4b95309b6df87248328e1c3791e47793
        token-validity: 1800 # 30 mins
spring:
  jpa:
    show_sql: true
    generate-ddl: false
    properties:
      hibernate.format_sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/zara_api

logging:
  file: logs/zara.log
  level:
    vn.zara: DEBUG
    root: INFO